# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a0ad4ff3568a173ed7634d65b6e181b196e1beca51c49b560f93abafb257c3d1cb3d53763fccf580680793c2d36b7333437519bc6e6941f8927ab9b40ded43

test:
  secret_key_base: 19e9141b941d10f5f0a098211bfd1fe5600ea128f96e2cbb6930f82bb67de2506294b56635d80a8fd6951f8517f540b1f6b7dec2919070451584c4256b2a20e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
